### PR TITLE
Breed/arch based init

### PR DESCRIPTION
**Pull request by BRReed**
the next thing to install is edk2 and i can't find a command to check if it is installed. i'll keep digging tomorrow but if you know something that won't be immediately obvious I'd love to be pushed in the right direction.

### CODE REVIEW

**Comment by BRReed** [comment]
So there's 2 possible ways that I can find. There's `pacman -Q | grep edk2-ovmf` which greps installed packages, if that succeeds continue, else install edk2-ovmf. Ther other way is to not have a conditional and have `pacman -S --needed edk2-ovmf`. --needed checks the package. If the package is not installed or not up to date it installs or updates it, otherwise doesn't do anything. I like the grep way better.

**Comment by stephenlauck** [comment]
I think you just need Qemu,? I haven't heard of edk2 nor have had to use it. Where are you reading about this?

**Comment by BRReed** [comment]
https://wiki.manjaro.org/index.php?title=Virt-manager Manjaro wiki

**Comment by stephenlauck** [comment]
> the next thing to install is edk2 and i can't find a command to check if it is installed. i'll keep digging tomorrow but if you know something that won't be immediately obvious I'd love to be pushed in the right direction.

`pacman -Qi <packageName>`

should set the exit code if installed or not installed.

**Comment by BRReed** [comment]
request review

**Review by stephenlauck — APPROVED** [review]

**Review by stephenlauck — CHANGES_REQUESTED** [review]
Wouldn't the assumption be that you've clone this repo and are running from inside the repo? You could also make the repo public and if you wanted could provide a curl|bash with the url to the script?

**Pull request merged**
